### ISSUE TITLE
Error: [$compile:tplrt]

### ISSUE THREAD

**Issue by nkdweb** [chrisgeo/progressindicator#3]
Hi

Round progress is working fine in firefox, but the same thing is not working in Internet Explorer and Google chrome.

It shows error in console, which is given below

> angular.min.js:117 Error: [$compile:tplrt] http://errors.angularjs.org/1.5.5/$compile/tplrt?p0=indicatorWidget&p1=indicator.html

Please let me know how to fix this issue

**Comment by chrisgeo** [comment]
@nkdweb This was just an example project and isn't actively maintained.

Sorry for the inconvenience.
